### PR TITLE
[EL-4090] Add ability to set initial values when adding fields to Search Builder

### PR DESCRIPTION
**Pull request by victor-ac**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licenced under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

[EL-4040](https://portal.digitalsafe.net/browse/EL-4090)

#### Description of Proposed Changes

Changed searchGroup controller to allow values to be set when adding search fields to any Search Group.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects-ng1_EL-4090

### CODE REVIEW

**Review by donna-marijne — CHANGES_REQUESTED** [review]
Thank you. I do not have a test case to verify this, but from looking at the code it does not appear that `findComponentByName` has a second parameter.

https://github.com/UXAspects/UXAspects-ng1/blob/master/src/ng1/directives/searchBuilder/searchGroup.controller.js#L78

The ticket you raised mentions `createComponent` - did you mean to add this parameter to the subsequent line in each case?

**Comment by victor-ac** [comment]
Thanks for catching that, @donna-marijne. Yes, I meant to change the calls to `createComponent`.

**Review by donna-marijne — APPROVED** [review]
Looks good, thank you for updating the tests as well.

**Review by ashley-hunter — APPROVED** [review]
All good thanks

**Pull request merged**
